-- 2024.09.23
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7 
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

-- 내가 제시한 틀린 답.
-- SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE DATEDIFF(END_DATE, START_DATE) >= 7
-- GROUP BY CAR_ID
-- ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

-- WHERE은 기본적인 조건절로서 우선적으로 모든 필드를 조건에 둘 수 있다.
-- HAVING은 GROUP BY 된 이후 특정한 필드로 그룹화 되어진 새로운 테이블에 조건을 줄 수 있다.
