-- 2024.09.23
SELECT YEAR(DIFFERENTIATION_DATE) YEAR, 
    (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE YEAR(DIFFERENTIATION_DATE) = YEAR) - SIZE_OF_COLONY as YEAR_DEV,
    ID
FROM ECOLI_DATA 
ORDER BY YEAR, YEAR_DEV

-- with를 사용한 풀이
-- with MAX_SIZE_TABLE as (
--     select YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE
--     from ECOLI_DATA
--     group by YEAR(DIFFERENTIATION_DATE)
-- )