-- 2024.09.23
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
ORDER BY PRICE DESC
LIMIT 1

-- 처음의 풀이. 성능은 위의 것이 더 좋다(서브쿼리 최소화).
-- SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
-- FROM FOOD_PRODUCT 
-- WHERE PRICE = (SELECT MAX(PRICE)
--                FROM FOOD_PRODUCT)