-- 2024.09.24
SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC

-- ORDER BY를 TOTAL_DISTANCE로 수행하지 않도록 주의.
-- (CONCAT으로 인해 문자열이 타입이 되어있는 상태)