-- 2024.09.20
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'Python')
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'C#')
ORDER BY ID;

-- JOIN을 사용하는 풀이
-- SELECT DISTINCT ID, EMAIL, FIRSTNAME, LASTNAME
-- FROM DEVELOPERS
-- JOIN SKILLCODES ON SKILLCODES.CODE & DEVELOPERS.SKILL_CODE = SKILLCODES.CODE
-- WHERE SKILLCODES.NAME IN ('C#', 'PYTHON')
-- ORDER BY ID;
