-- 2024.09.17
SELECT PT_NAME,	PT_NO, GEND_CD, AGE, IFNULL(TLNO,'NONE')  -- !
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD='W'
ORDER BY AGE DESC, PT_NAME ASC

-- NVL과 NVL2는 ORACLE 전용 함수
-- COALESCE는 연속성이 있는 IFNULL