SELECT ID,
    CASE  -- !
        WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
        WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SIZE
FROM ECOLI_DATA
ORDER BY ID

-- SELECT CASE WHEN 구문에서 조건식을 여러 개 사용할 수 있음